name: Build/release

on: 
  push:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build

      - name: Create releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/0.1.0/mac-universal/SpeedWords.app"
